# Creating arrays from Python List

First, we can use np.array to create arrays from Python lists:

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain
the same type. 

In [3]:
np.array([3.15,2,3,4,5]) # If types do not match, NumPy will upcast if possible

array([3.15, 2.  , 3.  , 4.  , 5.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype
keyword:


In [4]:
np.array([1,2,3,4,5],dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

Unlike Python lists, NumPy arrays can explicitly be multidimensional; here’s
one way of initializing a multidimensional array using a list of lists:


In [5]:
np.array([range(i,i+5) for i in [5,6,7]]) #2 dimensional Array

array([[ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

# Creating arrays from Scratch

In [6]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.full((2,3),5) # Create a 2x3 array filled with 5

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(0,25,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [10]:
np.linspace(1,14,5)

array([ 1.  ,  4.25,  7.5 , 10.75, 14.  ])

In [12]:
np.random.random((3,3))

array([[0.3154051 , 0.31664809, 0.21737572],
       [0.70819954, 0.27412878, 0.06319524],
       [0.95471384, 0.28937337, 0.14485672]])

In [13]:
np.random.randint(0,20,(3,3))

array([[15,  8,  6],
       [ 4, 12, 11],
       [ 3, 13,  9]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.empty(5)

array([ 1.  ,  4.25,  7.5 , 10.75, 14.  ])

In [16]:
np.empty([3,3])

array([[0.3154051 , 0.31664809, 0.21737572],
       [0.70819954, 0.27412878, 0.06319524],
       [0.95471384, 0.28937337, 0.14485672]])

# Basics of Numpy Array

Attributes of arrays:
Determining the size, shape, memory consumption, and data types of arrays

Indexing of arrays:
Getting and setting the value of individual array elements

Slicing of arrays:
Getting and setting smaller subarrays within a larger array

Reshaping of arrays:
Changing the shape of a given array

Joining and splitting of arrays:
Combining multiple arrays into one, and splitting one array into many



# Numpy array Array Attributes

In [17]:
a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,3))
c = np.random.randint(10, size=(3,4,5))

In [18]:
print("a ndim:",a.ndim)
print("b shape:",b.shape)
print("c size:",c.size)

a ndim: 1
b shape: (3, 3)
c size: 60


In [19]:
print("dtype of a:",a.dtype)
print("itemsize",b.itemsize,"bytes")
print("nbytes",c.nbytes,"bytes")

dtype of a: int32
itemsize 4 bytes
nbytes 240 bytes


# Array Indexing : Accesing Single Elements

 In a one-dimensional array, you can access the ith value (counting from
zero) by specifying the desired index in square brackets, just as with Python lists:


In [20]:
a[3] 

6

In [21]:
a

array([4, 6, 1, 6, 4, 1])

To index from the end of the array, you can use negative indices:


In [22]:
a[-1]

1

In [23]:
a[-3]

6

In a multidimensional array, you access items using a comma-separated tuple of
indices:


In [24]:
b

array([[0, 6, 9],
       [1, 6, 8],
       [6, 5, 4]])

In [25]:
b[0,1] # [row,column]

6

In [26]:
b[1,2]

8

In [27]:
b[2,-3]

6

You can also modify values using any of the above index notation:


In [28]:
b[1,1] = 9

In [29]:
b

array([[0, 6, 9],
       [1, 9, 8],
       [6, 5, 4]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means,
for example, that if you attempt to insert a floating-point value to an integer array, the
value will be silently truncated.


In [30]:
a

array([4, 6, 1, 6, 4, 1])

In [31]:
a[1] = 2.5

In [32]:
a

array([4, 2, 1, 6, 4, 1])

# Array Slicing: Accessing Subarrays


x[start:stop:step]


In [33]:
X = np.arange(15)

In [34]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
X[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
X[:10:2]

array([0, 2, 4, 6, 8])

In [37]:
X[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
X[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [39]:
X[::-2]

array([14, 12, 10,  8,  6,  4,  2,  0])

In [40]:
X[5::-2]

array([5, 3, 1])

# Multidimensional subarray

In [41]:
Y = np.random.randint(10,size=(3,4))

In [42]:
Y

array([[5, 9, 1, 3],
       [7, 4, 0, 5],
       [1, 7, 2, 4]])

In [43]:
Y[:,:]

array([[5, 9, 1, 3],
       [7, 4, 0, 5],
       [1, 7, 2, 4]])

In [44]:
Y[1:3,2:4]

array([[0, 5],
       [2, 4]])

In [45]:
Y[::2,::2]

array([[5, 1],
       [1, 2]])

In [46]:
Y[::-1,::-1]

array([[4, 2, 7, 1],
       [5, 0, 4, 7],
       [3, 1, 9, 5]])

# Accessing rows and columns

In [47]:
Y[:,0] #First column of Y

array([5, 7, 1])

In [48]:
Y[0,:] #First row of Y

array([5, 9, 1, 3])

In [49]:
Y[0] # Equivalent to Y[0,:]

array([5, 9, 1, 3])

# Subarrays as no-copy Views

In [51]:
print(Y)

[[5 9 1 3]
 [7 4 0 5]
 [1 7 2 4]]


In [53]:
Y_sub = Y[1:,2:] #Let’s extract a 2×2 subarray from this:

In [54]:
Y_sub

array([[0, 5],
       [2, 4]])

In [55]:
Y_sub[0,0] = 8 #Now if we modify this subarray, we’ll see that the original array is changed! Observe:

In [56]:
Y_sub

array([[8, 5],
       [2, 4]])

In [57]:
Y

array([[5, 9, 1, 3],
       [7, 4, 8, 5],
       [1, 7, 2, 4]])

This default behavior is actually quite useful: it means that when we work with large
datasets, we can access and process pieces of these datasets without the need to copy
the underlying data buffer.


# Creating copies of arrays

In [58]:
Y

array([[5, 9, 1, 3],
       [7, 4, 8, 5],
       [1, 7, 2, 4]])

In [63]:
Y_sub_copy = Y[1:,2:].copy()

In [64]:
Y_sub_copy

array([[8, 5],
       [2, 4]])

In [65]:
Y_sub_copy[0,0] = 10 #If we now modify this subarray, the original array is not touched:

In [66]:
Y_sub_copy

array([[10,  5],
       [ 2,  4]])

In [68]:
Y

array([[5, 9, 1, 3],
       [7, 4, 8, 5],
       [1, 7, 2, 4]])

# Reshaping Arrays

In [69]:
grid = np.arange(1,10).reshape((3,3))

The most flexible way of
doing this is with the reshape() method. For example, if you want to put the num‐
bers 1 through 9 in a 3×3 grid, you can do the following:

In [70]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


Note that for this to work, the size of the initial array must match the size of the
reshaped array.


In [72]:
X = np.array([1,2,3,4])

In [73]:
X.shape #One dimensional Array

(4,)

In [77]:
X_new = X.reshape((1,4)) #Two dimensional Array of rows and columns

In [78]:
X_new.shape

(1, 4)

In [79]:
X_new_1 = X.reshape((4,1))

In [80]:
X_new_1

array([[1],
       [2],
       [3],
       [4]])

In [81]:
X[np.newaxis,:]

array([[1, 2, 3, 4]])

In [82]:
X[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

# Array Concatenation and splitting

In [83]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [85]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
c = [34,56,78]

In [87]:
np.concatenate([a,b,c])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 34, 56, 78])

In [88]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.vstack([grid,c])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [34, 56, 78]])

# Splitting Arrays

The opposite of concatenation is splitting, which is implemented by the functions
np.split, np.hsplit, and np.vsplit


In [94]:
a = [1,2,3,4,5,6,7,8,9]

In [95]:
X1,X2,X3 = np.split(a,(3,5))

In [96]:
X1,X2,X3

(array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9]))

In [97]:
grid = np.arange(16).reshape((4,4))

In [98]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
upper,lower = np.vsplit(grid,[2])

In [104]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [105]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
left, right = np.hsplit(grid,[2])

In [107]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [108]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])